name: Deploy letsexploretanzania

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL_DEV }}
      DB_USERNAME: ${{ secrets.DB_USERNAME_DEV }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Deploy JAR to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
          source: 'target/letsexploretanzania-0.0.1-SNAPSHOT.jar'
          target: '/home/ubuntu/letsexploretanzania/'

      - name: Restart Spring Boot app on EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY_DEV }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USERNAME_DEV }}@${{ secrets.EC2_HOST_DEV }} << 'EOF'
          echo 'Stopping existing process...'
          pkill -TERM -f letsexploretanzania || true
          sleep 5
          echo 'Starting new process...'
          cd /home/ubuntu/letsexploretanzania/target || exit 1
          
          export DB_URL="${{ secrets.DB_URL_DEV }}"
          export DB_USERNAME="${{ secrets.DB_USERNAME_DEV }}"
          export DB_PASSWORD="${{ secrets.DB_PASSWORD_DEV }}"
          export SERVER_PORT="${{ secrets.SERVER_PORT_DEV }}"
          
          nohup java -jar letsexploretanzania-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          echo 'Process started'
          EOF
          rm private_key

